### ISSUE TITLE
Upload A demo Application  . 

### ISSUE THREAD

**Issue by muraza101** [groundctrl/shopping_mall#10]
rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
== 20160528114451 HatbmToHmt: migrating =======================================
-- add_column(:spree_option_types_prototypes, :id, :primary_key)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "spree_option_types_prototypes" does not exist
: ALTER TABLE "spree_option_types_prototypes" ADD "id" serial primary key
/home/jams/.rvm/gems/ruby-2.3.0@spe/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/home/jams/.rvm/gems/ruby-2.3.0@spe/gems/activerecord-4.2.6/lib/active_record/c

**Comment by dfreerksen** [comment]
Looks to be the same issue as https://github.com/groundctrl/shopping_mall/issues/11 Closing.
