### ISSUE TITLE
spree_option_types_prototypes Does not Exits 

### ISSUE THREAD

**Issue by muraza101** [groundctrl/shopping_mall#11]
when i run this command ,I'm facing this issue 
 rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
== 20160528114451 HatbmToHmt: migrating =======================================
-- add_column(:spree_option_types_prototypes, :id, :primary_key)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "spree_option_types_prototypes" does not exist
: ALTER TABLE "spree_option_types_prototypes" ADD "id" serial primary key
/home/jams/.rvm/gems/ruby-2.3.0@spe/gems/activerecord-4.2.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/home/jams/.rvm/gems/ruby-2.3.0@spe/gems/activerecord-4.2.6/lib/active_record/c

**Comment by dfreerksen** [comment]
What version of Spree are you running? `shopping_mall` has a migration to add a PK to a few tables (See the [migration here](https://github.com/groundctrl/shopping_mall/blob/master/db/migrate/20140611225105_hatbm_to_hmt.rb#L3)). `spree_option_types_prototypes` is one of those tables. The error is saying that table doesn't exist.

**Comment by muraza101** [comment]
I'm using spree 3.0.9 that gave the same error

**Comment by dfreerksen** [comment]
If Spree is giving you an error about the same table, then you probably haven't ran all of your migrations for Spree yet. Check out the [Spree install instructions](https://github.com/spree/spree/#installation-options). Once you do that then you can set up shopping_mall.

**Comment by muraza101** [comment]
Thanks Issue Resolved .
